### ISSUE TITLE
Compliation failure in Debian 10

### ISSUE THREAD

**Issue by tylerszabo** [lunaryorn/mdcat#170]
Building on Debian 10 fails after a5ab0dd2d225971a1c11ca9fb30daf27b59d33a8 (last good release `mdcat-0.21.1`)

Reproduce with the following `Dockerfile`:

```Dockerfile
FROM debian:10.6
RUN apt-get update && apt-get install -y cargo
CMD cargo install --git https://github.com/lunaryorn/mdcat.git --branch main
```

Build and run `docker build -t debian-mdcat:latest . && docker run --rm -it debian-mdcat:latest`

Output
```
error[E0658]: use of unstable library feature 'matches_macro'
  --> /root/.cargo/git/checkouts/mdcat-43b7df5bcbc5e636/271f696/src/terminal/size.rs:37:9
   |
37 |         matches!(self.partial_cmp(other), Some(Ordering::Equal))
   |         ^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
The following warnings were emitted during compilation:

warning: Failed to build manpage: No such file or directory (os error 2)

error: could not compile `mdcat`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mdcat v0.22.1 (https://github.com/lunaryorn/mdcat.git?branch=main#271f6961)`, intermediate artifacts can be found at `/tmp/cargo-installU0t1Wx`
```

**Comment by lunaryorn** [comment]
It still builds on CI so I guess you need a more recent Rust version.

**Comment by tylerszabo** [comment]
From a bit of searching it looks like this type of issue is pretty common with Rust projects on Debian and the suggested workaround is to use `rustup` rather than the repository version of Rust and Cargo. The following succeeded:

```Dockerfile
FROM debian:10.6
RUN apt-get update && apt-get install -y curl build-essential
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN source $HOME/.cargo/env
CMD cargo install --git https://github.com/lunaryorn/mdcat.git --branch main
```

Thanks for triaging :)
